version: "3"

networks:
  frontend:
# 設定backend子網路
  backend:

services:

# php
  php:
      container_name: php
      networks:
        - backend
      image: php:7.1-fpm
      expose:
        - 9000
      volumes:
        - ./../Site:/var/www/html/Site
        - ./../System:/var/www/html/System
        - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      tty: true

# nginx
  nginx:
      container_name: nginx
      networks:
        - frontend
        - backend
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./log/nginx:/var/log/nginx
        - ./../Site:/var/www/html/Site
        - ./../System:/var/www/html/System
