paths:
    migrations: ./migrations
    seeds: %%PHINX_CONFIG_DIR%%/db/seeds

environments:
    default_migration_table: phinxlog
    default_database: local

    local:
        adapter: mysql
        host: 127.0.0.1
        name: captaindb
        user: captain
        pass: 'deadbeefde'
        port: 3306
        charset: utf8mb4
        collation: utf8mb4_unicode_ci

version_order: creation